### ISSUE TITLE
Cargo build failing with error 'cannot be shared between threads safely

### ISSUE THREAD

**Issue by sureshbv** [borntyping/rust-riemann_client#5]
v0.6.0 is failing with the below error.
I updated the Cargo.toml file with version 0.7.0 and the build passed.
ubuntu@ubuntu-xenial:/rust/projects/fun2/my-riemann2$ cargo build --verbose
       Fresh winapi v0.2.8
       Fresh regex-syntax v0.3.9
       Fresh lazy_static v0.2.11
       Fresh strsim v0.5.2
       Fresh libc v0.2.34
       Fresh rustc-serialize v0.3.24
       Fresh utf8-ranges v0.1.3
       Fresh winapi-build v0.1.1
       Fresh protobuf v1.4.3
       Fresh libc v0.1.12
       Fresh memchr v0.1.11
       Fresh aho-corasick v0.5.3
       Fresh kernel32-sys v0.2.2
       Fresh thread-id v2.0.0
       Fresh thread_local v0.2.7
       Fresh regex v0.1.80
       Fresh docopt v0.6.86
   Compiling riemann_client v0.6.0
     Running `rustc --crate-name riemann_client /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_cli
ent-0.6.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="doco
pt"' --cfg 'feature="rustc-serialize"' -C metadata=6808c4b1696ba3a2 -C extra-filename=-6808c4b1696ba3a2 --out-dir /rust/
projects/fun2/my-riemann2/target/debug/deps -L dependency=/rust/projects/fun2/my-riemann2/target/debug/deps --extern doc
opt=/rust/projects/fun2/my-riemann2/target/debug/deps/libdocopt-54aceba036c3a58e.rlib --extern protobuf=/rust/projects/f
un2/my-riemann2/target/debug/deps/libprotobuf-555ad4088b5801da.rlib --extern libc=/rust/projects/fun2/my-riemann2/target
/debug/deps/liblibc-912115c9c5f29ac5.rlib --extern rustc_serialize=/rust/projects/fun2/my-riemann2/target/debug/deps/lib
rustc_serialize-b7218be0b8f1e639.rlib --cap-lints allow`
error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::State`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:282:6
    |
282 | impl ::protobuf::Message for State {
    |      ^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
    |
    = help: within `proto::State`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
    = note: required because it appears within the type `proto::State`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::State`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:439:6
    |
439 | impl ::protobuf::MessageStatic for State {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
    |
    = help: within `proto::State`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
    = note: required because it appears within the type `proto::State`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::Event`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:875:6
    |
875 | impl ::protobuf::Message for Event {
    |      ^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
    |
    = help: within `proto::Event`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
    = note: required because it appears within the type `proto::Event`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::Event`
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:1070:6
     |
1070 | impl ::protobuf::MessageStatic for Event {
     |      ^^^^^^^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
     |
     = help: within `proto::Event`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
     = note: required because it appears within the type `proto::Event`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::Query`
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:1253:6
     |
1253 | impl ::protobuf::Message for Query {
     |      ^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
     |
     = help: within `proto::Query`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
     = note: required because it appears within the type `proto::Query`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::Query`
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:1323:6
     |
1323 | impl ::protobuf::MessageStatic for Query {
     |      ^^^^^^^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
     |
     = help: within `proto::Query`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
     = note: required because it appears within the type `proto::Query`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::Msg`
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:1548:6
     |
1548 | impl ::protobuf::Message for Msg {
     |      ^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
     |
     = help: within `proto::Msg`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
     = note: required because it appears within the type `proto::Msg`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::Msg`
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:1671:6
     |
1671 | impl ::protobuf::MessageStatic for Msg {
     |      ^^^^^^^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
     |
     = help: within `proto::Msg`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
     = note: required because it appears within the type `proto::Msg`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::Attribute`
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:1850:6
     |
1850 | impl ::protobuf::Message for Attribute {
     |      ^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
     |
     = help: within `proto::Attribute`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
     = note: required because it appears within the type `proto::Attribute`

error[E0277]: the trait bound `std::cell::Cell<u32>: std::marker::Sync` is not satisfied in `proto::Attribute`
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/riemann_client-0.6.0/src/proto/mod.rs:1936:6
     |
1936 | impl ::protobuf::MessageStatic for Attribute {
     |      ^^^^^^^^^^^^^^^^^^^^^^^^^ `std::cell::Cell<u32>` cannot be shared between threads safely
     |
     = help: within `proto::Attribute`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<u32>`
     = note: required because it appears within the type `proto::Attribute`

error: aborting due to 10 previous errors

error: Could not compile `riemann_client`.

Caused by:
  process didn't exit successfully: `rustc --crate-name riemann_client /home/ubuntu/.cargo/registry/src/github.com-1ecc6
299db9ec823/riemann_client-0.6.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default"
 --cfg feature="docopt" --cfg feature="rustc-serialize" -C metadata=6808c4b1696ba3a2 -C extra-filename=-6808c4b1696ba3a2
 --out-dir /rust/projects/fun2/my-riemann2/target/debug/deps -L dependency=/rust/projects/fun2/my-riemann2/target/debug/
deps --extern docopt=/rust/projects/fun2/my-riemann2/target/debug/deps/libdocopt-54aceba036c3a58e.rlib --extern protobuf
=/rust/projects/fun2/my-riemann2/target/debug/deps/libprotobuf-555ad4088b5801da.rlib --extern libc=/rust/projects/fun2/m
y-riemann2/target/debug/deps/liblibc-912115c9c5f29ac5.rlib --extern rustc_serialize=/rust/projects/fun2/my-riemann2/targ
et/debug/deps/librustc_serialize-b7218be0b8f1e639.rlib --cap-lints allow` (exit code: 101)
ubuntu@ubuntu-xenial:/rust/projects/fun2/my-riemann2$

**Comment by borntyping** [comment]
I'm unable to support older versions of the library - their dependencies are fixed at the time they are uploaded. This appears to be a problem with the `protobuf` library no longer working on the current version of Rust. You're better off upgrading to `0.7.0`, sorry.
